#!/usr/bin/env bash

script_dir="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
dry="0"

while [[ $# > 0 ]]; do
    if [[ $1 == "--dry" ]]; then
        dry="1"
    fi
    shift
done

log() {
    if [[ $dry == "1" ]]; then 
        echo "[DRY_RUN]: $@"
    else 
        echo "$@"
    fi
}
execute(){
    log "execute $@"
    if [[ $dry == "1" ]]; then 
        return 
    fi
    "$@"
}

cd $script_dir

copy_dir() {
    pushd $1
    form=$1
    to=$2
    dirs=$(find . -mindepth 1 -maxdepth 1 -type d)
    for dir in $dirs; do
        execute rm -rf $to/$dir
        execute cp -r $dir $to/$dir
    done
    popd > /dev/null
}

copy_file() {
    from=$1
    to=$2
    name=$(basename $from)
    execute rm $from
    execute cp $from $to/$name
}


log "----------------- dev-env ---------------"

copy_dir .config $HOME/.config
# copy_file .spconf $HOME
# copy_file .specialrc ~/

